const DATA_URL='data/saldo_presupuestario.json';
let datos=[];let chartCC=null;let chartEstado=null;
const fmt=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
const fmtPct=new Intl.NumberFormat('es-CL',{maximumFractionDigits:1});
function n(v){if(typeof v==='number')return v;if(!v)return 0;const limpio=String(v).replace(/\$/g,'').replace(/\./g,'').replace(/,/g,'').replace(/\s/g,'');const num=Number(limpio);return Number.isFinite(num)?num:0;}
function t(v){return String(v??'').trim();}
async function iniciar(){const res=await fetch(DATA_URL);const payload=await res.json();datos=payload.rows||[];document.getElementById('fechaActualizacion').textContent='Actualizado: '+(payload.updated_at||'sin fecha');poblarFiltros();conectarEventos();render();}
function poblarFiltros(){llenarSelect('filtroCC',[...new Set(datos.map(d=>t(d.cc)).filter(Boolean))].sort());llenarSelect('filtroCuenta',[...new Set(datos.map(d=>t(d.cuenta)).filter(Boolean))].sort());}
function llenarSelect(id,valores){const sel=document.getElementById(id);valores.forEach(v=>{const opt=document.createElement('option');opt.value=v;opt.textContent=v;sel.appendChild(opt);});}
function conectarEventos(){['filtroCC','filtroCuenta','busqueda'].forEach(id=>document.getElementById(id).addEventListener('input',render));document.getElementById('limpiarFiltros').addEventListener('click',()=>{document.getElementById('filtroCC').value='';document.getElementById('filtroCuenta').value='';document.getElementById('busqueda').value='';render();});}
function filtrar(){const cc=t(document.getElementById('filtroCC').value);const cuenta=t(document.getElementById('filtroCuenta').value);const q=t(document.getElementById('busqueda').value).toLowerCase();return datos.filter(d=>{if(cc&&t(d.cc)!==cc)return false;if(cuenta&&t(d.cuenta)!==cuenta)return false;if(q){const hay=[d.cc,d.nombre_cc,d.cuenta].map(t).join(' ').toLowerCase();if(!hay.includes(q))return false;}return true;});}
function sumar(rows,campo){return rows.reduce((acc,d)=>acc+n(d[campo]),0);}
function render(){const rows=filtrar();document.getElementById('kpiOriginal').textContent=fmt.format(sumar(rows,'presupuesto_original'));document.getElementById('kpiAjustes').textContent=fmt.format(sumar(rows,'ajustes_netos'));document.getElementById('kpiVigente').textContent=fmt.format(sumar(rows,'presupuesto_vigente'));document.getElementById('kpiComprometido').textContent=fmt.format(sumar(rows,'comprometido'));document.getElementById('kpiDisponible').textContent=fmt.format(sumar(rows,'disponible'));document.getElementById('contadorFilas').textContent=rows.length+' registros';renderTabla(rows);renderCharts(rows);}
function agregarCelda(tr,valor,clase){const td=document.createElement('td');td.textContent=valor;if(clase)td.className=clase;tr.appendChild(td);}
function renderTabla(rows){const body=document.getElementById('tablaBody');body.replaceChildren();rows.slice().sort((a,b)=>t(a.cc).localeCompare(t(b.cc))||t(a.cuenta).localeCompare(t(b.cuenta))).forEach(d=>{const vigente=n(d.presupuesto_vigente);const comp=n(d.comprometido);const disp=n(d.disponible);const pct=vigente?(comp/vigente)*100:0;const tr=document.createElement('tr');agregarCelda(tr,t(d.cc));agregarCelda(tr,t(d.nombre_cc));agregarCelda(tr,t(d.cuenta));agregarCelda(tr,fmt.format(n(d.presupuesto_original)),'num');agregarCelda(tr,fmt.format(n(d.ajustes_netos)),'num');agregarCelda(tr,fmt.format(vigente),'num');agregarCelda(tr,fmt.format(comp),'num');agregarCelda(tr,fmt.format(disp),'num '+(disp<0?'warn':'good'));agregarCelda(tr,fmtPct.format(pct)+'%','num');body.appendChild(tr);});}
function porCC(rows){const m=new Map();rows.forEach(d=>{const key=t(d.cc)||'Sin CC';const label=(key+' '+t(d.nombre_cc)).trim();const actual=m.get(key)||{label,vigente:0};actual.vigente+=n(d.presupuesto_vigente);m.set(key,actual);});return [...m.values()].sort((a,b)=>b.vigente-a.vigente).slice(0,8);}
function renderCharts(rows){const top=porCC(rows);if(chartCC)chartCC.destroy();chartCC=new Chart(document.getElementById('chartCC'),{type:'bar',data:{labels:top.map(d=>d.label),datasets:[{label:'Presupuesto vigente',data:top.map(d=>d.vigente)}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#e5e7eb'}}},scales:{x:{ticks:{color:'#94a3b8'}},y:{ticks:{color:'#94a3b8'}}}}});if(chartEstado)chartEstado.destroy();chartEstado=new Chart(document.getElementById('chartEstado'),{type:'doughnut',data:{labels:['Comprometido','Disponible'],datasets:[{data:[sumar(rows,'comprometido'),Math.max(sumar(rows,'disponible'),0)]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#e5e7eb'}}}}});}
iniciar().catch(err=>{console.error(err);document.getElementById('fechaActualizacion').textContent='Error cargando datos';});
